### ISSUE TITLE
[Problem] Sketcher symmetry ignores external geometry.

### ISSUE THREAD

**Issue by mbelt** [realthunder/FreeCAD#1006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.21 (Development)

### Full version info

```shell
[code]
OS: Arch Linux
Word size of FreeCAD: 64-bit
Version: 0.21.0.38935 (Git)
Build type: Release
Branch: makepkg
Hash: a0d6ece6c0e7b64dca6b2066a7d57b982a9f2a17
Python 3.11.6, Qt 5.15.12, Coin 4.0.2, Vtk 9.3.0, OCC 7.7.2
Locale: English/United States (en_US)
Installed mods: 
  * freecad.gears 1.2.0
[/code]
```

### Subproject(s) affected?

Sketcher

### Problem description

The sketcher buttons that copy geometry (symmetry, clone, array) do not copy external geometry.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by realthunder** [comment]
The above commit enables copying of external geometry. There is some limitation at the moment. It is due to the fact that there is no constraints on the external geometries or between them. Say you copy a set of connected external edges, there is no coincident constraint between them, so you'll have to connect them manually. There is also complication if you copy geometry that constrains to an external geometry. Because it is not obvious visually which external geometry are constrained against. See below for example. The geometry is connected to the arrow pointed external edge, but not the other one. If you copy the edge together with the wrong external edge, the copies won't be connected. This problem exists for normal geometry copying as well, but it will be more obvious when external geometry is involved, since there is no constraints between them in the first place.

![image](https://github.com/user-attachments/assets/141a6500-761a-4d91-9145-9e69e0eb8e7a)
