### ISSUE TITLE
option for not saving mesh / cashed data

### ISSUE THREAD

**Issue by wohltat** [realthunder/FreeCAD#186]
As i understand it FreeCAD cashes the mesh created from the original geometry. This mesh data is also saved to objectname.xml in the FCStd file or to the directory when saving to a directory. Since this mesh data is recreated when recomputing, it is kind of redundant and only serves the function of speed improvement.

It would be nice to have the option to choose not to save it and let it recompute automatically. This would ease sharing and collaborating on files.

I tried to just remove the `<![CDATA[]]>` sections from `Pad001.xml` and it still works to open the project. There was an error message
```
01:15:49  <App> PropertyContainer.cpp(492): saved_as_directory#Pad001.Shape (Part::PropertyPartShape) restore error.
```
 and i had to manually recompute but after that the document seems fine.
This reduced the file size from 225kB to 5.6kB, which is a factor of 40x. 

[saved_as_directory.zip](https://github.com/realthunder/FreeCAD/files/7214393/saved_as_directory.zip)
[saved_as_directory_original.zip](https://github.com/realthunder/FreeCAD/files/7214394/saved_as_directory_original.zip)

**Comment by realthunder** [comment]
You can change the document property `ForceXML` to 1. Simply click the document icon in the tree view, and change it in the property editor. Then save the project as directory. You'll find the shapes are saved as separate files such as `Fusion.Shape.brp`. If you don't want share the shape data, just add an ignore entry (e.g. `.gitignore`) for this type of file, assuming you are using some sort of version control on the directory (which you should, because there is no auto backup when save as directory). BTW, you may also want to ignore the topo naming file (e.g. `Fusion.Shape.Map.txt`). Not all shapes has topo naming.

Currently, loading a project without shape only produce error output in the report view, I'll change it to mark the error in the object. Be warned though, FreeCAD is a rapidly evolving project without much backward compatibility guarantee. There is also variables like the version of OCCT used on other's distro to be considered. It is very likely to get error on a full recomputet. To guarantee successful data exchange, you are advised to try full recompute using a specific release image, and notify the other side to use the save release image for loading.

**Comment by wohltat** [comment]
I did as you said and tried to delete all .brp and .Shape.Map.txt files but then i cannot recompute the document. 
Deleting only the .brp files also didn't work. I used the project from above (first post).
I saved it before opening, to ensure it cannot be a version incompatibility.

At first nothing appears. Some objects can be recomputed when marked manually but some like a Fillet had an error.
For example

```
<Exception> FeatureDressUp.cpp(122): Invalid edge link: ?Edge8
Recompute failed! Please check report view.
```

Is this addressed in your previous commit already?

Would be very useful to have this working to collaborate on a document with version control like git.

**Comment by realthunder** [comment]
This invalid edge link is the inherent danger I mentioned earlier about not saving shapes. Because the underlying modeling algorithm will change from time to time. Even if FreeCAD itself does not change, OCCT the CAD kernel may change from version to version. With my topo naming and saved shape, the algorithm changing problem can be reduced to some extent. What it does is that before doing a recompute, it will save, e.g. the referenced edge for the fillet, and then search for that edge after recomputation. I will improve on this in the future. Maybe to store those referenced geometry separately just in case.

But even this has a chance to fail. The only way to guarantee a reproducible result is to try it yourself. Pick a release, and do a full recompute (right click document icon and select `Mark for recompute`). Manually fix any error. Repeat a full recompute until there is no error. You can then be sure that the document can be restored with the same release of the same platform that you used.
