### ISSUE TITLE
Additive Pocket suddenly appeared in my document

### ISSUE THREAD

**Issue by wsteffe** [realthunder/FreeCAD#191]
With reference of same structure uploaded in issue #178 (now closed) I have just discovered that a pocket (first pocket in Body named CAVITY_TOP) was missing because the related operation was set to additive instead of subtractive. I do not think to have ever made this selection, which in my opinion doesn't make sense for a pocket. A pocket should always be subtractive. I think that it is the result of a change in the FC code aimed to introduce Additive/Subtractive/Intersecting options in all (or most) Body features.
I agree with with this choice (it is more general and more coincise) but then the Pocket Feature/Icon should disappear and it should be replaced by Pad with the Subtractive option. All documents written before the change should be automatically converted to the new logic.

**Comment by realthunder** [comment]
The new `AddSubType` property was introduced in 03e5529f965, 07.27, which unfortunately, introduced a nasty bug that failed to initialize the property for those subtractive features, making them additive. It was fixed in 9ce2a9238d1, 09.14. If you have built and used my branch in this period to save any of the document containing PartDesign features, then you'll need to fix the problem by either manually change all subtractive features' `AddSubType` property to `Subtractive`, or, open and save the file in some older [release](https://drive.google.com/drive/folders/1_Di2T8k0X0B7yDfbH2g55Ia4bnADbKFz?usp=sharing).

The icon of `Pocket`, or most PartDesign feature for that matter, will in fact change according to its `AddSubType`. If you look closely, an `Additive Pocket` has yellow in the middle of the icon, while a normal `Subtractive Pocket` is red instead. `Pocket` and `Pad` are currently implemented as two different features with some difference in code, unlike, say `Loft` and `Pipe`, which uses the exact same code for its `Additive` and `Subtractive` variant.

**Comment by wsteffe** [comment]
"It was fixed in 9ce2a92". Ok thanks.

Regarding the additive Pocket in my opinion it doesn't make sense. Pocket is synonym of hole and by definition it should be subtractive. I think that also pad word has intrinsically an additive meaning.
A better (more general) term which can be used with both options (additive and subtractive) is extrude.
The problem is that in FC extrude is a different feature. I used it to make faces instead of solids. If this (the fact that it can make surfaces) is the only difference, in my opinion it would be better to unify Pad, Pocket and Extrude in a single general Extrude with an additional option: Make solids or Make surfaces.

**Comment by realthunder** [comment]
The main motivation of adding 'AddSubType' is for the newly introduced 'Intersecting' type, and also the 'New shape' option which is originally available through the 'NewSolid' property. It is true that 'Additive' and 'Subtractive' types may not make sense to some features. I just don't make any unnecessary limitations here. Who knows what the user may find any use of it, especially if expression is involved. It is much harder to dynamically change a feature type then a property value.

**Comment by wsteffe** [comment]
> It is much harder to dynamically change a feature type then a property value.
Ye, I may understand.
I would still prefer a more concise User Interface with less redundancies (in example a general Extrude instead of a Pad, a Pocket, and a special Extrude). But I may live with it as it is.
