### ISSUE TITLE
[Issue] Expression editor background depends on the Stylesheet name. 

### ISSUE THREAD

**Issue by StudioPetrikas** [realthunder/FreeCAD#369]
Hi, 
I've made style-sheet that is mostly dark in colour. However, I am not able to change the background of the input boxes of the expression editor. 

It took me 2 hours to realise that the colour of the expression editor backgrounds are dependent on the name of the stylesheet. 

Apparently, if the filename is called "Stylesheet Dark.qss" it will load a dark background, and everything else will load a light background. 

**How to reproduce**:
Create 2 empty .qss files in the /gui/stylesheets folder. "Something.qss" and "Something Dark.qss"

**Expected results:**
Ideally, the background depends on a property in the stylesheet, not the name

**Current Result:**
Expression editor can only have a dark background colour if the filename contains the word "Dark"

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.406.26244 +4692 (Git)
Build type: Release
Branch: LinkDaily
Hash: 0c8e437ef38cdc5dd087529ce6825c6a2a130868
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: English/United Kingdom (en_GB)

**Comment by realthunder** [comment]
The expression editor style is highly configurable due to a user submitted PR. The text and background colors are determined by the Output window log/error/warning color and stylesheet name, and stylesheet explicit setting. The logic behind it is somewhat convoluted. Anyway, see the example [here](https://github.com/realthunder/FreeCAD/blob/5403a4484cf549dfeca7a138312ea11791305fa7/src/Gui/DlgExpressionInput.h#L58) on how to set it explicitly using stylesheet.

**Comment by StudioPetrikas** [comment]
That's perfect! I really need to learn to read code and find all the qproperties myself, sorry about this.
