### ISSUE TITLE
Custom Work Plane Selection Not Working

### ISSUE THREAD

**Issue by cadmarx** [realthunder/FreeCAD#410]
Custom work plane selection not working (screenshot attached).

OS: macOS 12.3
Word size of FreeCAD: 64-bit
Version: 2022.407.26244 +4693 (Git)
Build type: Release
Branch: LinkDaily
Hash: 9610830a8fd492b3b3d96f8328507c80f1437cda
Python version: 3.9.10
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: C/Default (C)

<img width="1556" alt="Screen Shot 2022-05-15 at 5 07 32 PM" src="https://user-images.githubusercontent.com/92646037/168494031-61e40805-d931-4fde-81fc-11886a183026.png">

**Comment by bambukouk** [comment]
This is not an assembly issue?

**Comment by cadmarx** [comment]
Could anyone please let me know where this post has been moved to? Sorry I am not sure about the rules here.

**Comment by bambukouk** [comment]
> Could anyone please let me know where this post has been moved to? Sorry I am not sure about the rules here.
![Screenshot from 2022-05-18 09 46 38](https://user-images.githubusercontent.com/50301871/168998260-75759012-391c-4ffd-9363-41fb32624c8d.png)

Clearly you know where it is (since you are posting here :+1: )
Your issue pertains to FreeCAD Linkstage3 branch (and not to Assembly3) and that's where it belongs :+1: 
It is a bit confusing at first...

**Comment by discip** [comment]
@cadmarx
Please close this issue as you were directed to the right spot. 😊
