### ISSUE TITLE
Freecad crashes When using the fill command.

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD#423]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.430.26244 +4758 (Git)
Build type: Release
Branch: LinkDaily
Hash: b024b876480a533018fdc702145e9e38f8c54ba6
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: English/United States (en_US) 

As can be seen in the video free cad crashes when I use the fill command. 

https://user-images.githubusercontent.com/92737149/169657169-c0358838-a4ea-42e3-91c5-cfd964a86d50.mp4  

I know there is some distance between the wires. But freecad should not crash because of this.      

![1](https://user-images.githubusercontent.com/92737149/169657217-b6abb2ea-f489-44bd-8959-19cccee17509.jpg)         

![11](https://user-images.githubusercontent.com/92737149/169657223-f19c2fe5-c68a-4f1e-91b0-3e267cec21e2.jpg)  

![111](https://user-images.githubusercontent.com/92737149/169657227-a09f3a1c-30e5-4a12-b8af-05184d62c4a7.jpg)  

File   

[1.zip](https://github.com/realthunder/FreeCAD/files/8747826/1.zip)

**Comment by realthunder** [comment]
The crash is due to an OCC bug as mentioned in code comment [here](https://github.com/realthunder/FreeCAD/blob/3f41f321039021fd628765164f00ff8ec4f28f2b/src/Mod/Part/App/TopoShapeEx.cpp#L4171).

BTW, with commit 8916f67e4cb20557dfa7e12f551fe2ecec44c7bc, it is now possible to create this kind of filled face with the green `SubShapeBinder`, if you don't need any extra face or edge constrain.

https://user-images.githubusercontent.com/1207888/169925049-2258c4ec-206e-4181-ad11-e4f7851e3461.mp4

**Comment by realthunder** [comment]
Just for reference. There will be another crash if creating a (non-filled) surface using the edges of the existing face in the test file.

![Screenshot from 2022-05-26 07-35-32](https://user-images.githubusercontent.com/1207888/170386502-721dfbe9-5266-4790-b4ed-0bfa5b678a5b.png)

**Comment by hamza00789** [comment]
Coming this distance is also a problem. 
The distance should not have come to this place. 
 
![1111](https://user-images.githubusercontent.com/92737149/170396177-12c25cb3-06dd-4d55-963d-24025502f718.jpg)
 
[distance 1.zip](https://github.com/realthunder/FreeCAD/files/8775523/distance.1.zip)
