### ISSUE TITLE
Copy Paste Body into part and Reordering it

### ISSUE THREAD

**Issue by wsteffe** [realthunder/FreeCAD#473]
Hy RT,
 Sometime I need to  copy a Body placed in a Part into a new Body that I would like to stay in the same part.
But I have observed that the paste always put the body in the document root  outside of the Part even if the Part was selected before. It is possible to drag the copied body into the part but this operation may be tricky if the structure tree is so long that origin and destination of drag are not visible at the same time. It would be more natural if  the pasted object were automatically placed in the pre-selected container.

Another problem I have is related with the position of the pasted Body inside of the containing Part.
After dragging a body into a Part it is always placed at the and of the existing bodies.
I have tried to drag it in a different position but I were never successful with this kind of operation. Most of the time it messed the data structure with the cancellation of an existing body placed near the end point of drag.

**Comment by wsteffe** [comment]
Regarding the reordering of Bodies in a Part: would it possible to extend the context command "Move Object After other Object" which works with features in a Body to works also with Bodies in a Part ?

**Comment by realthunder** [comment]
Could you please provide a sample project showing the problem you have when reordering a body in a Part with several bodies?

**Comment by wsteffe** [comment]
Here it is: [RX_HelicFilter.FCStd.zip](https://github.com/realthunder/FreeCAD/files/9037438/RX_HelicFilter.FCStd.zip)
I have just created with copy/paste the Body named helic7 .
It is not very important but I tried (unsuccesfully) to move it upward in the list of bodies  associated with Part named CMP_HelicFilter.

**Comment by realthunder** [comment]
When you drag and drop, the icon will hint the current operation. Sometimes, the current operation is not sensible for some object. Use `Ctrl` , `Alt`, or `Ctrl + Alt` to change the operation. In your case, you can use `Alt` to change to the reorder operation.

Also, there are some cross linking problems in your bodies. I guess that could be a problem when you try to reorder. Because the `Part` group will try to auto correct the cross linking when recompute. To disable the auto correct, use the following option. I'll see what I can do about the paste into Part group. 

![image](https://user-images.githubusercontent.com/1207888/177113380-0819145b-6db5-455d-bc20-fc4d698e5b99.png)

**Comment by wsteffe** [comment]
Thanks, In fact after setting Allow cross coordinate links I was able to change the position of helic7.
But I can not understand the effect of Ctrl, Alt and Ctrl+Alt. I can not see any hint message when I press them.
I think that, to avoid a bad usage of drag-drop, it would be more safe an explicit command such as "Move Object After other Object"

**Comment by realthunder** [comment]
Drag and drop provides more context information than `Move object after other`. To be more precise, the command should be `Move object after another in a given parent`.

https://user-images.githubusercontent.com/1207888/177136115-a2c79633-e516-4d49-a7b0-8a96ff2099e6.mp4
