### ISSUE TITLE
Spreadsheet: Cell Units Improperly editing

### ISSUE THREAD

**Issue by master-puller** [realthunder/FreeCAD#505]
Realthunder:
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2022.709.28846 (Git)
Build type: Release
Branch: LinkStage3
Hash: c880c050c5f7601e4bae6740de71500edf2be0c7
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United States (en_US)

# Expected behavior:
Setting cell unit in spreadsheet workspace applies unit conversion to input value without units
`Properties -> Display Unit -> Unit string "nm" -> close -> "98" -> 98 nm`
# Actual behavior:
Displays unit in default document units; `98 ≠ 98mm`
`Properties -> Display Unit -> Unit string "nm" -> close -> "98" -> 98,000,000 nm`

# Screenshot:
![image](https://user-images.githubusercontent.com/19511301/179556513-aeaf7d0f-6817-4da0-8fae-f49e1e08f257.png)

**Comment by master-puller** [comment]
Screenshot shows cells with `98` in each cell, units are different

**Comment by realthunder** [comment]
The actual behavior is by design. For unit-less value, FreeCAD always treats it as if it is in standard unit (i.e. `mm/kg/s/degree`), no matter what. Or else, the same document may open differently on system with different settings. What you can change is the display unit, which will convert the standard unit to the given one before display. What you can also do is to enter unit explicitly, in which case, the value you entered is actually stored as a string, and will be parsed as expression in runtime, and internally evaluated to value in standard unit behind the scene.

If you really have a problem with this design choice, you can raise your voice in the forum, as this behavior is inherited from upstream.
