### ISSUE TITLE
Changing style sheet in preferences causes strange dots to appear on parts when in shadow view

### ISSUE THREAD

**Issue by Jakeo-93** [realthunder/FreeCAD#524]
![Screenshot_20220803_202525](https://user-images.githubusercontent.com/110573979/182730442-cec0aee7-b9d4-46a5-8808-daa9d2430f8b.png)

os is arch linux using either the latest snap pack or appimage , switching off the default style sheet in preferences causes the preference box to hang for a while when opening and causes these black dots to appear on parts when in shadow mode.

**Comment by ForgeThrall** [comment]
Issue replicated on Windows 10, using [Midnight UI](https://forum.freecadweb.org/viewtopic.php?t=55779) on a fresh install

**Comment by realthunder** [comment]
The bug has been fixed in 7ac4493ad224d2ef670daee3ce558080defd608a.

Until the next release, as a workaround, after you've activated shadow mode, manually changed the Document property Epsilon to 0.00001

![image](https://user-images.githubusercontent.com/1207888/193178996-44ab0582-2931-4036-8a6c-10560ceed165.png)

**Comment by discip** [comment]
@Jakeo-93
Please remember closing solved issues. 😊
