### ISSUE TITLE
Wrong Shapestring text displaying

### ISSUE THREAD

**Issue by vovodroid** [realthunder/FreeCAD#628]
```
OS: Windows 10 (10.0)
Word size of FreeCAD: 64-bit
Version: 2022.1021.26244 +5249 (Git)
Build type: Release
Branch: LinkDaily
Hash: d307b5c936403e8dca3f24b5c1e64bd16c88b28d
Python version: 3.9.13
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United States (en_US)
```

![image](https://user-images.githubusercontent.com/8691781/201175738-26fe9dae-8941-4d0f-9bf5-4a301cbd5fae.png)

The same file created in FC 0.20.1 looks ok:

![image](https://user-images.githubusercontent.com/8691781/201175960-6497b3e2-4e36-4e92-9cdb-9cf769e077aa.png)

Font file included in zip.

[3D.zip](https://github.com/realthunder/FreeCAD/files/9983648/3D.zip)

**Comment by vovodroid** [comment]
Actually file created with FC 0.20.1 looks good before recomputation:

![image](https://user-images.githubusercontent.com/8691781/201300244-8881f674-ee2a-4917-9629-9cfe8b274c1c.png)

And after recomputation:

![image](https://user-images.githubusercontent.com/8691781/201300391-a7dc10c4-b503-4977-8e2a-06f6fddbc5ae.png)

**Comment by julia-m-stephenson** [comment]
Hiya,

I'm seeing the square between each character in Linkstage but not in vanilla 0.20.1 even after a recompute.

![image](https://user-images.githubusercontent.com/52968628/208888805-d1dc2301-dc80-435a-84b1-2d055de20bde.png)

vs 0.20.1

![image](https://user-images.githubusercontent.com/52968628/208888911-78d496f6-353c-45b1-9224-adcbe45c26c9.png)

Is this a UTF16 / UTF8 problem?

I can provide my (minimal criminal) files if desired?

Here are my version details

Linkstage
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.1112.26244 +5306 (Git)
Build type: Release
Branch: LinkDaily
Hash: c64e4a49244a1c0ce9fd6455d18aa919d0db9c80
Python version: 3.10.6
Qt version: 5.15.4
Coin version: 4.0.1
OCC version: 7.6.3
Locale: English/United Kingdom (en_GB)

Vanilla 0.20.1
[code]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.1.29410 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: f5d13554ecc7a456fb6e970568ae5c74ba727563
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: English/United Kingdom (en_GB)
[/code]

**Comment by julia-m-stephenson** [comment]
I thought I'd try the latest Linkstage release. 

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.1128.26244 +5318 (Git)
Build type: Release
Branch: LinkDaily
Hash: d45d221edcc7a757eb4e4eb638da0db5ed2759aa
Python version: 3.10.8
Qt version: 5.15.4
Coin version: 4.0.1
OCC version: 7.6.3
Locale: English/United Kingdom (en_GB)

I still get the same issue.

Here's what happens if I open the correctly working file from Linkstage build.

![image](https://user-images.githubusercontent.com/52968628/209547719-97a2d496-2936-44bb-9534-5e4da2e64d91.png)

Here's the error text for easy copy paste 

`12:07:47  ----------------
12:07:47  GuiCommand: ShapeString
12:07:47  Pick ShapeString location point:
12:10:12  <PropShape> PropertyTopoShape.cpp(422): Pending recompute for generating element map: Richards_Halt_0_20_1_Bounding_Box_Method2#Body
12:10:12  <PropShape> PropertyTopoShape.cpp(422): Pending recompute for generating element map: Richards_Halt_0_20_1_Bounding_Box_Method2#Sketch
12:10:12  <PropShape> PropertyTopoShape.cpp(422): Pending recompute for generating element map: Richards_Halt_0_20_1_Bounding_Box_Method2#Pad
12:10:12  <PropShape> PropertyTopoShape.cpp(422): Pending recompute for generating element map: Richards_Halt_0_20_1_Bounding_Box_Method2#Pad
12:10:12  <PropShape> PropertyTopoShape.cpp(422): Pending recompute for generating element map: Richards_Halt_0_20_1_Bounding_Box_Method2#Sketch001
12:10:12  <PropShape> PropertyTopoShape.cpp(422): Pending recompute for generating element map: Richards_Halt_0_20_1_Bounding_Box_Method2#Pocket
12:10:12  <PropShape> PropertyTopoShape.cpp(422): Pending recompute for generating element map: Richards_Halt_0_20_1_Bounding_Box_Method2#Pocket
12:10:12  <PropShape> PropertyTopoShape.cpp(422): Pending recompute for generating element map: Richards_Halt_0_20_1_Bounding_Box_Method2#ShapeString
12:10:12  <PropShape> PropertyTopoShape.cpp(422): Pending recompute for generating element map: Richards_Halt_0_20_1_Bounding_Box_Method2#Pad001
12:10:12  <PropShape> PropertyTopoShape.cpp(422): Pending recompute for generating element map: Richards_Halt_0_20_1_Bounding_Box_Method2#Pad001
12:10:12  Traceback (most recent call last):
  File "C:\Program Files\Realthunder\FreeCAD-asm3-Daily-Win-Conda-Py3.10-20221128-x86_64\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
<class 'ModuleNotFoundError'>: No module named 'draftviewproviders.view_shapestring'
12:10:21  <App> PropertyLinks.cpp(401): Richards_Halt_0_20_1_Bounding_Box_Method2#Sketch001.Support auto change element reference Richards_Halt_0_20_1_Bounding_Box_Method2#Pad Face6 -> ;#1e;:G0;XTR;:H911:8,F.Face6
`
So the issue appears to be a missing module 'draftviewproviders.view_shapestring' has this been renamed / refactored in link stage?

I have the file which works okay in vanilla 0.22.1 I'll try and upload it as a test case for you.

Thanks Julia

**Comment by julia-m-stephenson** [comment]
Here is my test file hope it helps :-)

[Richards_Halt_0_20_1_Bounding_Box_Method.FCStd.gz](https://github.com/realthunder/FreeCAD/files/10303384/Richards_Halt_0_20_1_Bounding_Box_Method.FCStd.gz)

**Comment by julia-m-stephenson** [comment]
Having found where that module is in Vanilla freecad I can see the module is missing from the realthunder branch

C:\Program Files\Realthunder\FreeCAD-asm3-Daily-Win-Conda-Py3.10-20221128-x86_64\Mod\Draft\draftviewproviders

![image](https://user-images.githubusercontent.com/52968628/209548969-4bf42e36-248d-4bb4-8bd5-6952b24a45e0.png)

But it is in the vanilla freecad directory.

C:\Program Files\FreeCAD 0.20\Mod\Draft\draftviewproviders

![image](https://user-images.githubusercontent.com/52968628/209549072-c4791b9c-82a8-42a2-99b6-4849134bb52d.png)

Is this just a build issue?

Thanks
Julia

**Comment by julia-m-stephenson** [comment]
My bad it looks like it was a bug in the Python 3.10 build for windows only. See this forum post [https://forum.freecadweb.org/viewtopic.php?style=4&f=3&t=71036](url)

Fixed in vanilla Freecad by this commit.
[https://github.com/FreeCAD/FreeCAD/commit/3b29cf18be](url)

Hopefully this get fixed with next release. 

In the mean time the FreeCAD-asm3-Daily-Win64-LibPack-Py3.8-20221128 version seems to be fine!
