### ISSUE TITLE
FreeCAD_asm3 does not warn of keyboard shortcut reassignment conflicts

### ISSUE THREAD

**Issue by nathaneltitane** [realthunder/FreeCAD#733]
I have just spent some time changing shortcuts into a more logical set of combinations, and upon setting the same sequance for two unrelated commands within the sketcher selections, the preferences dialog did not prompt or warn of the conflict for this assignment.

**Comment by realthunder** [comment]
It does not warn because it can now handle the same shortcut assigned to different commands, possibly in different workbench. Duplicated shortcut is listed in priority list, where you can reorder to resolve conflict, if those command may appear in the same context.

![image](https://user-images.githubusercontent.com/1207888/222428697-561b781b-019b-4f91-9f15-31344c718a9b.png)

**Comment by nathaneltitane** [comment]
Understood! Thank you.
