### ISSUE TITLE
App crash when deleting any constraint from the tree view in A3 (2023.08.11 Windows version)

### ISSUE THREAD

**Issue by lyuabe** [realthunder/FreeCAD#881]
I update my previous 2023.05 version (not available anymore). everything was working fine, but with the latest 2023.08.11 update and I realized that whatever project I use, when I delete a constraint, the app crashes instantly. I deleted the config folder completely but this did not solve the issue.

I am attaching an animated GIF show it (this shown for a very small "demo" FreeCAD file, but it crashes whatever the file/project I use).

![FreeCAD-asm3-Daily-Win-Conda-Py3 10-20230131-x86_64](https://github.com/realthunder/FreeCAD/assets/119549238/3b26ab34-24f3-4e41-8d50-dba2ffa39cba)

PS: where are the FreeCAD log files located so I can investigate what coudl go wrong?

**Comment by realthunder** [comment]
This is the same cause as #877, and has been fixed already. I'll make a new release soon.

**Comment by lyuabe** [comment]
Thank you (and congratualtions for the great job btw). Where are FreeCAD logs located so that it can maybe provide useful information for debugging?

**Comment by not-a-number-dot-org** [comment]
This problem is really crippling. Can you please issue a new release.

[code]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 2023.811.0.14555 (Git shallow)
Build type: Release
Branch: HEAD
Hash: d31fdf6ab71bf52a96d5d3b81f3b8349bca24e27
Python 3.11.4, Qt 5.15.6, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.2
Locale: French/France (fr_FR)
[/code]

**Comment by lyuabe** [comment]
Fixed in 20231018! Thanks!
