### ISSUE TITLE
Error - destruction of the model when one of the elements is removed from the body

### ISSUE THREAD

**Issue by tiket18** [realthunder/FreeCAD#96]
![Снимок экрана от 2021-02-02 12-02-47](https://user-images.githubusercontent.com/18741088/106577127-0a073b80-654f-11eb-9086-b0cca845432a.png)
![Снимок экрана от 2021-02-02 12-02-36](https://user-images.githubusercontent.com/18741088/106577132-0b386880-654f-11eb-870f-09dadb13a6fe.png)

Here is a ready and made without errors body, Sketch016 is made on the surface in it, after its removal the model is destroyed. This is a fairly old bug in the program, it's just that earlier projects were more complex and (probably) it would have been harder to "catch" the error.

I sent the file by e-mail.

**Comment by realthunder** [comment]
This is not a bug per sa. But it's handling can be improved. The reason for this is because you are cross linking external geometry in `Sketch015`. The sketch is referring to geometries that are outside of the body. This is not allowed. With recent changes in sketch external geometry selection, this should not be possible. The correct way is to use a (green) SubShapeBinder to import external geometries into the body, and then map external geometry on the binder.

I'll probably change the error handling by output some warning only.

**Comment by luzpaz** [comment]
@realthunder good to close?

**Comment by luzpaz** [comment]
@realthunder ping
