### ISSUE TITLE
[Problem] Erroneous cyclic dependency

### ISSUE THREAD

**Issue by vovodroid** [realthunder/FreeCAD#979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

0.20 (Release)

### Full version info

```shell
[code]
OS: Windows 10 build 19044
Word size of FreeCAD: 64-bit
Version: 2024.322.0.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 20240322stable)
Hash: da98001cfe5cc50cb2e9e4c241626d07dd4b06f5
Python 3.11.8, Qt 5.15.6, Coin 4.0.1, Vtk 9.2.5, OCC 7.7.1
Locale: English
Installed mods: 
  * Curves 0.6.13
  * ThreadProfile 1.87.0
[/code]
```

### Subproject(s) affected?

None

### Problem description

While creating Pad "Cyclic dependency" error appears, so there is no such dependency.

![image](https://github.com/realthunder/FreeCAD/assets/8691781/384f8011-28e6-471f-bbc0-cd6fa9b780cb)

![image](https://github.com/realthunder/FreeCAD/assets/8691781/a6d1a241-657a-41a4-8e57-9a7b648ccf35)

[500cyclic.zip](https://github.com/realthunder/FreeCAD/files/14787113/500cyclic.zip)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by realthunder** [comment]
The tag icon with a green dot marks the current tip of the body. Any new feature will be inserted after this tip feature and becomes the new tip. This is how you can easily add features in the middle of the history. The cyclic dependency is formed because the sketch is attached to a feature that is after the new pad. In body, all features depends on previous features on the history line.

 If you move the tip by accident, you can right click the last Pad and choose `Set body tip` to move the tip. 

![image](https://github.com/realthunder/FreeCAD/assets/1207888/6f13c86e-d3d8-433b-8d71-2121f098b5ad)
